### ISSUE TITLE
This repository is over its data quota - How to solve?

### ISSUE THREAD

**Issue by avielas** [moabitcoin/holy-edge#12]
Hi

I got the following error when trying to run the command from "Training data & Models":

user@user-desktop:~/DL/holy-edge$ sudo git lfs fetch && git lfs pull
Fetching master
Git LFS: (0 of 2 files) 0 B / 585.83 MB                                                                                                                                                      
batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/harsimrat-eyeem/holy-edge.git/info/lfs'

**Comment by SeanSyue** [comment]
I've found the site where VGG-16 models weights file is accessible. The URL link is down below:
    https://mega.nz/#!YU1FWJrA!O1ywiCS2IiOlUCtCpI6HTJOMrneN-Qdv3ywQP5poecM
--------------------------------------------------------------------------------------------------------------------
Notice that in the vgg16.py file within the hed/model directory, the first line indicates the GitHub website where the similar code was inherited from. You can just get into the website, where cited
    To use the VGG networks, the npy files for VGG16 NPY or VGG19 NPY has to be downloaded.
This is where I've found the URL link above.

**Comment by h44rd** [comment]
Hello! I am not able to access the link as it's insecure. Is there a parallel link through which it could be downloaded?

**Comment by xavysp** [comment]
Hi,
 I have the same problem:
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file 'vgg16.npy' as a pickle
could you guys update such file (vgg16.npy)
please

**Comment by sandhawalia** [comment]
https://github.com/moabitcoin/holy-edge/issues/5#issuecomment-349274597
