### ISSUE TITLE
cannot clone pre-trained model file

### ISSUE THREAD

**Issue by HRLTY** [moabitcoin/holy-edge#14]
Hi, it seems that the hed-model-5000.meta cannot be cloned because of data quota exceeded. Could you provide a new link for this file? Thanks!
The current content is just a placeholder:

`version https://git-lfs.github.com/spec/v1
oid sha256:71ef9f6fb10c25654e3f16708da7efc55bdbcc02cae75b84134a7ce051f728f9
size 60853279`

**Comment by Elaine10** [comment]
hi, do you mean that you cannot load vgg16.npy?

ftp://mi.eng.cam.ac.uk/pub/mttt2/models/vgg16.npy

md5 is equal to that in this repo.

**Comment by SeanSyue** [comment]
I've got the same problem.

**Comment by K-Leon** [comment]
An upload by someone who could clone it would be great!

**Comment by charliememory** [comment]
Maybe this can be helpful  https://github.com/moabitcoin/holy-edge/issues/5#issuecomment-349274597

**Comment by sandhawalia** [comment]
https://github.com/moabitcoin/holy-edge/issues/5#issuecomment-349274597
