### ISSUE TITLE
Training does not converge

### ISSUE THREAD

**Issue by xjock** [moabitcoin/holy-edge#17]
[32m[08 May 2018 21h43m00s][INFO] [7428/100000] TRAINING loss : 0.1480998396873474[0m
[32m[08 May 2018 21h43m02s][INFO] [7429/100000] TRAINING loss : 0.16046211123466492[0m
[32m[08 May 2018 21h43m03s][INFO] [7430/100000] TRAINING loss : 0.15747885406017303[0m
[32m[08 May 2018 21h43m03s][INFO] [7430/100000] VALIDATION error : 0.2499309927225113[0m
[32m[08 May 2018 21h43m04s][INFO] [7431/100000] TRAINING loss : 0.14023230969905853[0m
[32m[08 May 2018 21h43m06s][INFO] [7432/100000] TRAINING loss : 0.15643279254436493[0m
[32m[08 May 2018 21h43m07s][INFO] [7433/100000] TRAINING loss : 0.1568005532026291[0m
[32m[08 May 2018 21h43m09s][INFO] [7434/100000] TRAINING loss : 0.13042421638965607[0m
[32m[08 May 2018 21h43m10s][INFO] [7435/100000] TRAINING loss : 0.13672024011611938[0m
[32m[08 May 2018 21h43m11s][INFO] [7436/100000] TRAINING loss : 0.16531457006931305[0m
[32m[08 May 2018 21h43m12s][INFO] [7437/100000] TRAINING loss : 0.1498943716287613[0m
[32m[08 May 2018 21h43m14s][INFO] [7438/100000] TRAINING loss : 0.1395827680826187[0m
[32m[08 May 2018 21h43m15s][INFO] [7439/100000] TRAINING loss : 0.16227483749389648[0m
[32m[08 May 2018 21h43m16s][INFO] [7440/100000] TRAINING loss : 0.14770230650901794[0m
[32m[08 May 2018 21h43m17s][INFO] [7440/100000] VALIDATION error : 0.24861328303813934[0m
[32m[08 May 2018 21h43m19s][INFO] [7441/100000] TRAINING loss : 0.13362529873847961[0m
[32m[08 May 2018 21h43m20s][INFO] [7442/100000] TRAINING loss : 0.1269095093011856[0m
[32m[08 May 2018 21h43m21s][INFO] [7443/100000] TRAINING loss : 0.15405525267124176[0m
[32m[08 May 2018 21h43m23s][INFO] [7444/100000] TRAINING loss : 0.1538567692041397[0m
[32m[08 May 2018 21h43m25s][INFO] [7445/100000] TRAINING loss : 0.16362397372722626[0m
[32m[08 May 2018 21h43m26s][INFO] [7446/100000] TRAINING loss : 0.15053629875183105[0m
[32m[08 May 2018 21h43m28s][INFO] [7447/100000] TRAINING loss : 0.1497960239648819[0m
[32m[08 May 2018 21h43m29s][INFO] [7448/100000] TRAINING loss : 0.14233416318893433[0m
[32m[08 May 2018 21h43m30s][INFO] [7449/100000] TRAINING loss : 0.13796669244766235[0m
[32m[08 May 2018 21h43m32s][INFO] [7450/100000] TRAINING loss : 0.13414344191551208[0m
[32m[08 May 2018 21h43m32s][INFO] [7450/100000] VALIDATION error : 0.2629392445087433[0m
[32m[08 May 2018 21h43m34s][INFO] [7451/100000] TRAINING loss : 0.16665637493133545[0m
[32m[08 May 2018 21h43m35s][INFO] [7452/100000] TRAINING loss : 0.14615492522716522[0m
[32m[08 May 2018 21h43m37s][INFO] [7453/100000] TRAINING loss : 0.09095730632543564[0m
[32m[08 May 2018 21h43m38s][INFO] [7454/100000] TRAINING loss : 0.15941087901592255[0m
[32m[08 May 2018 21h43m40s][INFO] [7455/100000] TRAINING loss : 0.15737438201904297[0m
[32m[08 May 2018 21h43m42s][INFO] [7456/100000] TRAINING loss : 0.15094870328903198[0m
[32m[08 May 2018 21h43m43s][INFO] [7457/100000] TRAINING loss : 0.1470448523759842[0m
[32m[08 May 2018 21h43m44s][INFO] [7458/100000] TRAINING loss : 0.15349626541137695[0m
[32m[08 May 2018 21h43m46s][INFO] [7459/100000] TRAINING loss : 0.12288802117109299[0m
[32m[08 May 2018 21h43m47s][INFO] [7460/100000] TRAINING loss : 0.1600235551595688[0m
[32m[08 May 2018 21h43m48s][INFO] [7460/100000] VALIDATION error : 0.2703090310096741[0m
[32m[08 May 2018 21h43m49s][INFO] [7461/100000] TRAINING loss : 0.13551127910614014[0m
[32m[08 May 2018 21h43m51s][INFO] [7462/100000] TRAINING loss : 0.15077351033687592[0m
[32m[08 May 2018 21h43m52s][INFO] [7463/100000] TRAINING loss : 0.13134542107582092[0m
[32m[08 May 2018 21h43m53s][INFO] [7464/100000] TRAINING loss : 0.14744725823402405[0m
[32m[08 May 2018 21h43m55s][INFO] [7465/100000] TRAINING loss : 0.14557607471942902[0m
[32m[08 May 2018 21h43m56s][INFO] [7466/100000] TRAINING loss : 0.1406044214963913[0m
[32m[08 May 2018 21h43m58s][INFO] [7467/100000] TRAINING loss : 0.1485893577337265[0m
[32m[08 May 2018 21h43m59s][INFO] [7468/100000] TRAINING loss : 0.1595202535390854[0m
[32m[08 May 2018 21h44m00s][INFO] [7469/100000] TRAINING loss : 0.16567926108837128[0m
[32m[08 May 2018 21h44m01s][INFO] [7470/100000] TRAINING loss : 0.15977224707603455[0m
[32m[08 May 2018 21h44m02s][INFO] [7470/100000] VALIDATION error : 0.19350607693195343[0m

Any idea？

**Comment by yogurt233** [comment]
I meet the same question,exactly, the training loss doesn't descend from the begining.I want to know why.

**Comment by sravanje** [comment]
Facing the same issue.

**Comment by xjock** [comment]
Already given up，please refer to https://github.com/zju3dv/snake
