### ISSUE TITLE
This repository is over its data quota. Purchase more data packs to restore access

### ISSUE THREAD

**Issue by magneter** [moabitcoin/holy-edge#20]
Hi.It is great to find your code. I searched HED articles And codes many days.
 But When I clone from github ,I get the message--This repository is over its data quota. Purchase more data packs to restore access.

And I have no idea to fix it. Could you give me some advice?

**Comment by doantientai** [comment]
I am having the same trouble. Could you please upload the pretrained model to another place like google drive?

**Comment by sandhawalia** [comment]
https://github.com/moabitcoin/holy-edge/issues/5#issuecomment-349274597
