### ISSUE TITLE
Could anyone can provide a pretrained model in google drive or baiduyun?

### ISSUE THREAD

**Issue by drui000** [moabitcoin/holy-edge#21]
I just want to inference some images , but I can't open the download link and come up against some problems with git lfs.

**Comment by charliememory** [comment]
Maybe this can be helpful https://github.com/moabitcoin/holy-edge/issues/5#issuecomment-349274597

**Comment by sandhawalia** [comment]
https://github.com/moabitcoin/holy-edge/issues/5#issuecomment-349274597
