### ISSUE TITLE
Is it true that you didn't train the parameters of VGG16?

### ISSUE THREAD

**Issue by Mistariano** [moabitcoin/holy-edge#28]
Hi,

Thank you very much for the brilliant work. :)

I just wonder why you set the parameters of VGG16 as constants:

https://github.com/moabitcoin/holy-edge/blob/98cf525de5ed787e58b521be2e60a03b9da4826c/hed/models/vgg16.py#L163

According to the paper, the objective function minimizes both *W* and *w*, but it seems like you only minimized *w*

**Comment by mengxingkong** [comment]
i have the same question, had you resolved it?

**Comment by sandhawalia** [comment]
Initially to train faster we didn't fine-tune the Convnet backbone. Initially we just train the HED head. One can fine-tune the model one the deconv layers are trained.
