### ISSUE TITLE
Some questions in your 'paper-notes.md'

### ISSUE THREAD

**Issue by CangHaiQingYue** [moabitcoin/holy-edge#8]
Hi, I read your notes in the 'paper-notes.md', have you ever try your idea in the notes. Especially, the side_output_5 is not as good as in paper.

**Comment by harsimrat-eyeem** [comment]
Hi, 
`side_output_5` works at the largest scale of the reconstructing the edges and its quality would depend on the deconvolutions layer. I have used very simple version of the deconv layers but yes they could be improved. I plan to update it soon.

**Comment by CangHaiQingYue** [comment]
Hi,
I'd tried to use slim to recode your work, but failed. side_1 was same as yours, but side_4 and side_5 is too bad. There are my code for 'side_layer'..what's problem with those code, can you help me.
    def side_layer(self, inputs, scope, num_output):
            side = slim.conv2d(inputs, 1, [1,1], stride=1,
                                activation_fn=None,
                                weights_initializer=tf.zeros_initializer(),
                                biases_initializer=tf.zeros_initializer(),
                                scope=scope+'_conv')
             side = slim.conv2d_transpose(side,1, [2*num_output,2*num_output],
                                         activation_fn=None,
                                         biases_initializer=None,
                                         stride = num_output,
                                         weights_initializer=tf.truncated_normal_initializer(stddev=0.1),
                                         scope=scope+'_transopse')

**Comment by harsimrat-eyeem** [comment]
Hi, 

Could you please paste the complete code snippet here formatted with github's recommended methods. Also could you please explain what are you trying to improve and how. This way I can read through your code and give appropriate feedback.

**Comment by CangHaiQingYue** [comment]
And can you add precision-recall curve step in the test...
